CREATE TABLE game (
  id        BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  game_uid  UUID NOT NULL,
  date      DATE NOT NULL,
  buy_in    DECIMAL NOT NULL,

  CONSTRAINT pk_game PRIMARY KEY (id),
  CONSTRAINT uk_game_uid UNIQUE (game_uid)
);

CREATE TABLE player (
  id          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  player_uid  UUID NOT NULL,
  username    VARCHAR(32) NOT NULL,

  CONSTRAINT pk_player PRIMARY KEY (id),
  CONSTRAINT uk_player_uid UNIQUE (player_uid),
  CONSTRAINT uk_player_username UNIQUE (username)
);

CREATE TABLE game_prize (
  id          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  game_id     BIGINT NOT NULL,
  player_id   BIGINT NOT NULL,
  position    INT NOT NULL,
  amount      DECIMAL NOT NULL,

  CONSTRAINT pk_game_prize PRIMARY KEY (id),
  CONSTRAINT fk_game_prize_game_id FOREIGN KEY (game_id) REFERENCES game (id),
  CONSTRAINT fk_game_prize_player_id FOREIGN KEY (player_id) REFERENCES player (id)
);

CREATE TABLE buy_in (
  id        BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  game_id   BIGINT NOT NULL,
  player_id BIGINT NOT NULL,
  count     INT    NOT NULL DEFAULT 1,

  CONSTRAINT pk_buy_in PRIMARY KEY (id),
  CONSTRAINT fk_buy_in_game_id FOREIGN KEY (game_id) REFERENCES game (id),
  CONSTRAINT fk_buy_in_player_id FOREIGN KEY (player_id) REFERENCES player (id),
  CONSTRAINT uk_buy_in UNIQUE (game_id, player_id),
  CONSTRAINT chk_buy_in_count CHECK ( count > 0 )
);
